<template lang="pug">
b-form
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Name:",
    label-for="foodName"
  )
    b-input-group
      b-form-input#foodName
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Quantity:",
    label-for="foodQuantity"
  )
    b-input-group(append="gr")
      b-form-input#foodQuantity
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Carbohydrates:",
    label-for="foodCarbohydrates"
  )
    b-input-group(append="gr")
      b-form-input#foodCarbohydrates
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Protein:",
    label-for="foodProtein"
  )
    b-input-group(append="gr")
      b-form-input#foodProtein
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Fat:",
    label-for="foodFat"
  )
    b-input-group(append="gr")
      b-form-input#foodFat
  b-form-group(
    label-cols="5",
    label-cols-lg="2",
    label="Calories:",
    label-for="foodCalories"
  )
    b-input-group(append="kcal")
      b-form-input#foodCalories
</template>
